export var FILE_STATUS;
(function (FILE_STATUS) {
    FILE_STATUS[FILE_STATUS["ERROR"] = 0] = "ERROR";
    FILE_STATUS[FILE_STATUS["WAITING"] = 1] = "WAITING";
    FILE_STATUS[FILE_STATUS["COMPRESSING"] = 2] = "COMPRESSING";
    FILE_STATUS[FILE_STATUS["FINISHED"] = 3] = "FINISHED";
})(FILE_STATUS || (FILE_STATUS = {}));
export var COMPRESSION_STATUS;
(function (COMPRESSION_STATUS) {
    COMPRESSION_STATUS[COMPRESSION_STATUS["WAITING"] = 0] = "WAITING";
    COMPRESSION_STATUS[COMPRESSION_STATUS["COMPRESSING"] = 1] = "COMPRESSING";
    COMPRESSION_STATUS[COMPRESSION_STATUS["FINISHED"] = 2] = "FINISHED";
    COMPRESSION_STATUS[COMPRESSION_STATUS["FINISHED_ALL_ERRORS"] = 3] = "FINISHED_ALL_ERRORS";
})(COMPRESSION_STATUS || (COMPRESSION_STATUS = {}));
export var MESSAGE_LEVEL;
(function (MESSAGE_LEVEL) {
    MESSAGE_LEVEL[MESSAGE_LEVEL["ERROR"] = 0] = "ERROR";
    MESSAGE_LEVEL[MESSAGE_LEVEL["WARNING"] = 1] = "WARNING";
    MESSAGE_LEVEL[MESSAGE_LEVEL["INFO"] = 2] = "INFO";
    MESSAGE_LEVEL[MESSAGE_LEVEL["SUCCESS"] = 3] = "SUCCESS";
})(MESSAGE_LEVEL || (MESSAGE_LEVEL = {}));
export var COMPRESSION_MODE;
(function (COMPRESSION_MODE) {
    COMPRESSION_MODE[COMPRESSION_MODE["QUALITY"] = 0] = "QUALITY";
    COMPRESSION_MODE[COMPRESSION_MODE["SIZE"] = 1] = "SIZE";
})(COMPRESSION_MODE || (COMPRESSION_MODE = {}));
export var MAX_SIZE_UNIT;
(function (MAX_SIZE_UNIT) {
    MAX_SIZE_UNIT[MAX_SIZE_UNIT["BYTE"] = 1] = "BYTE";
    MAX_SIZE_UNIT[MAX_SIZE_UNIT["KILOBYTE"] = 1000] = "KILOBYTE";
    MAX_SIZE_UNIT[MAX_SIZE_UNIT["MEGABYTE"] = 1000000] = "MEGABYTE";
})(MAX_SIZE_UNIT || (MAX_SIZE_UNIT = {}));
